config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  root 'sessions#new'
  resources :users
  resources :statuses do
    resources :comments
  end

  delete '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :status
  belongs_to :user
  validates_presence_of :user
  validates_presence_of :body
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :statuses

  has_attached_file :photo,
     					styles: { medium: "300x300#", thumb: "100x100#" },
   					default_url: ":style/missing.jpg",
                         :storage => :s3,
                         url: ":s3_domain_url",
                         path: "/:class/:attachment/:id_partition/:style/:filename",
                         s3_region: 'us-east-1',
                         :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

     def s3_credentials
       {
         :bucket => ENV["S3_BUCKET_NAME"],
         :access_key_id => ENV["S3_ACCESS_KEY_ID"],
         :secret_access_key => ENV["S3_SECRET_ACCESS_KEY"]
       }
     end
     validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Status.find(params[:status_id]).comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to status_path @comment.status
  end

  private
  def comment_params
    params.require(:comment).permit(:user, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path @user
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def index
  end

  def show
    @status = Status.find(params[:id])
  end

  def new
  end

  def create
    @status = Status.new(status_params)
    @status.user = current_user
    if @status.save
      redirect_to user_path @status.user
    end
  end

  def edit
  end

  def update
    @status = Status.find(params[:id])
    @status.update(status_params)
    @status.user = current_user
    if @status.save
      redirect_to user_path @status.user
    end
  end

  def destroy
    @status = Status.find(params[:id])

      if @status.user != current_user
        redirect_to users_path @users_path
      else
        @status.comments.destroy_all
          @status.destroy
          redirect_to user_path current_user
        end
  end

  private
  def status_params
    params.require(:status).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show]

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @status = Status.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path @user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      redirect_to users_path
  end

  # Only these fields are allowed on forms:
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :bio, :species, :photo, :age, :tagline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Anilog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
      </form>
      <ul class="nav navbar-nav navbar-right">

          <% if logged_in? %>
            <li><%= link_to 'All Anilogs', users_path %></li>
            <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li>  <%= link_to 'Logout', logout_path, method: :delete%></li>
          <% else %>
            <li>  <%= link_to 'Login', new_session_path %></li>
          <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anilog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>

<%= render '/layouts/nav' %>

<div class="container">


<%= yield %>
</div>

</body>
</html>

app/views/statuses/show.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

<style media="screen">
  body{
    font-size: 30px;
    font-family: 'Gloria Hallelujah', cursive;
}
  h1{
    font-size: 65px;
}
</style>

</head>

<body>

<br>

<%= link_to 'Go Back', user_path(@status.user)  %>

<hr>

<strong>My Status:</strong> <%= @status.body %> <br>

<!--  Form for creating a comment-->
<%= form_for [@status, @status.comments.build] do |f| %>
  <%= f.text_area :body, placeholder: 'enter comment here', class: 'form-control' %> <br>
  <%= f.submit %>
<% end %>

<!--  allows comments to be rendered for each staus-->
<% @status.comments.each do |comment| %>
  <%= comment.body %> <br>
  <%= comment.created_at %> <br>
<% end %>

</body>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<head>

  <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
  <style media="screen">

    body{
      font-size: 30px;
      font-family: 'Gloria Hallelujah', cursive;
}
    h1{
      font-size: 50px;
}
  </style>

</head>

<body>

<h1>Edit Your Profile</h1>

<%= link_to 'Go Back', user_path(@user) %>

<!--  form for editing user profiles-->
<%= form_for @user do |f| %>
  <strong>Name:</strong> <%= f.text_field :name, placeholder: 'name', class: 'form-control' %> <br>
  <strong>Breed:</strong> <%= f.text_field :species, placeholder: 'breed', class: 'form-control' %> <br>
  <strong>Age:</strong>  <%= f.text_field :age, placeholder: 'age', class: 'form-control' %> <br>
  <strong>Bio:</strong>  <%= f.text_area :bio, placeholder: 'bio', class: 'form-control' %> <br>
  <%= f.submit 'Update Profile' %>
<% end %>

</body>

app/views/users/index.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

<style media="screen">

  body{
    font-size: 20px;
    font-family: 'Gloria Hallelujah', cursive;
}
  h1{
    font-size: 55px;
}
</style>
</head>

<body>

<h1 class="text-center">All Anilogs</h1>

<%= link_to 'My Profile', user_path(@user) %>

<!--  index of user profiles-->
<% @users.each do |u| %>
  <hr>
  <%= link_to image_tag(u.photo.url(:medium), {class: 'img-circle'}), user_path(u) %> <br>
  Name:   <%= u.name %> <br>
  Breed:  <%= u.species %> <br>
  Age:    <%= u.age %> <br>
    <% if(u.statuses.last) %>
      Status: <%= u.statuses.last.body %> <br>
    <% end %>
<% end %>

</body>

app/views/users/new.html.erb
<head>

  <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
  <style media="screen">

    body{
      font-size: 30px;
      font-family: 'Gloria Hallelujah', cursive;
}
    h1{
      font-size: 50px;
}
  </style>

</head>

<body>

  <h1 class="text-center">Create A Profile</h1>

<!-- Form to create a new profile -->

<%= form_for @user, html: { multipart: true } do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name, class:"form-control", placeholder: 'pet name' %> <br>
  <%= f.label :species, 'Breed' %> <br>
  <%= f.text_field :species, class:"form-control", placeholder: 'pet breed' %> <br>
  <%= f.label :age %> <br>
  <%= f.text_field :age, class:"form-control", placeholder: 'pet age' %> <br>
  <%= f.label :bio %> <br>
  <%= f.text_field :bio, class:"form-control", placeholder: 'pet description' %> <br>
  <%= f.label :email %> <br>
  <%= f.text_field :email, class:"form-control", placeholder: 'pet owner email address' %> <br>
  <%= f.label :password %> <br>
  <%= f.text_field :password, class:"form-control", placeholder: 'password' %> <br>
  <input class="btn btn-default" type="submit" value="Submit">
<% end %>

</body>

app/views/users/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">

<style media="screen">

  body{
    font-size: 30px;
    font-family: 'Gloria Hallelujah', cursive;
}
  h1{
    font-size: 50px;
}
.pic_upl{
  font-size: 15px;
}
</style>

<body>

<h1 class="text-center">Meet...</h1>

<hr>

<!--  form for uploading photos-->
<div class="pic_upl">
  <%= form_for @user, html: {multipart: true} do |f| %>
  <%= f.label 'Upload a Profile Pic!' %> <br>
  <%= f.file_field :photo %> <br>
  <%= f.submit 'Upload Photo'%>
  <% end %>
</div>

<!--  displays image -->
<div class="text-center">
  <%= image_tag @user.photo.url(:medium), {class: "img-circle"} %> <br>
  Age: <%= @user.age %> <br>
  Breed: <%= @user.species %> <br>
</div>

<blockquote class="blockquote-reverse">
<%= @user.bio %>
</blockquote>

<hr>

<!--  form for updating user status-->
<%= form_for @status do |f| %>
  <%= f.text_area :body, placeholder: 'What are you up to?', class: 'form-control' %><br>
  <%= f.submit 'Update Status' %>
<% end %>

<!--  displays the status and allows user to show status to see comments and delete status-->
<% @user.statuses.each do |s| %>
  <hr>
  <%= s.body %> <br>
  <%= link_to "Show", status_path(s) %> <br>
  <%= link_to "Delete", status_path(s), method: :delete %>
<% end %>

<hr>

</body>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>